import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { Cpu, Network, Thermometer, HardDrive, Zap, Activity, ArrowRight, CheckCircle } from "lucide-react";

const AIReadyDataCenter = () => {
  const coreInfrastructure = [
    {
      title: "GPU-Accelerated Compute",
      description: "Designed to support high-density GPU deployments for massively parallel processing, crucial for training complex AI models.",
      icon: Cpu
    },
    {
      title: "High-Throughput Networking",
      description: "Low-latency, high-bandwidth fabric ensures rapid data movement between nodes, eliminating bottlenecks during intensive workloads.",
      icon: Network
    },
    {
      title: "Advanced Liquid Cooling",
      description: "Engineered to efficiently manage the extreme heat generated by dense GPU clusters, ensuring optimal performance and hardware longevity.",
      icon: Thermometer
    },
    {
      title: "Scalable Architecture",
      description: "Robust, high-density power distribution that scales efficiently to support growing computational demands and future hardware generations.",
      icon: Zap
    }
  ];

  const specifications = [
    { label: "Rack Density", value: "Up to 100 kW+" },
    { label: "GPU Capacity", value: "Multiple configs" },
    { label: "Network", value: "400G+ bandwidth" },
    { label: "Cooling", value: "Liquid + Air hybrid" },
    { label: "Uptime", value: "99.99%" },
    { label: "Monitoring", value: "Real-time analytics" }
  ];

  const useCases = [
    {
      title: "AI Research & Development",
      description: "A powerful, flexible environment for academic or enterprise research teams developing next-generation AI models."
    },
    {
      title: "Cloud Service Providers",
      description: "Scalable, highly efficient infrastructure to deliver AI-as-a-Service (AIaaS) and machine learning platforms."
    },
    {
      title: "Financial Services",
      description: "High-performance computing for algorithmic trading, fraud detection, and risk analysis."
    },
    {
      title: "Life Sciences & Healthcare",
      description: "GPU-accelerated infrastructure for drug discovery, genomic sequencing, and medical imaging analysis."
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-secondary/20">
      {/* Hero Section */}
      <section className="relative py-20 lg:py-32 bg-gradient-hero">
        <div className="absolute inset-0 tech-grid opacity-10"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <Badge variant="outline" className="mb-6 border-primary/30 text-primary">
            AI Infrastructure
          </Badge>
          <h1 className="text-4xl lg:text-6xl font-display font-bold mb-6">
            AI-Ready Data Centers
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            Purpose-built infrastructure optimized for AI workloads, machine learning, and next-generation computing.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button variant="hero" size="lg" asChild>
              <Link to="/contact">
                Get Quote
                <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
            <Button variant="glass" size="lg" asChild>
              <Link to="/demo">Talk to an AI Specialist</Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Core Infrastructure */}
      <section className="py-20 lg:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-5xl font-display font-bold mb-6">
              Core <span className="text-g2c-green">Infrastructure</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Essential components that power high-performance AI and machine learning.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {coreInfrastructure.map((item, index) => {
              const Icon = item.icon;
              const bgColor = index % 2 === 0 ? "bg-primary" : "bg-accent";
              return (
                <Card key={index} className="bg-gradient-card border-primary/20">
                  <CardHeader>
                    <div className={`w-16 h-16 mb-4 ${bgColor} rounded-xl flex items-center justify-center`}>
                      <Icon className="w-8 h-8 text-white" />
                    </div>
                    <CardTitle>{item.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-muted-foreground">{item.description}</p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* Performance Specifications */}
      <section className="py-20 lg:py-32 bg-gradient-card">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-5xl font-display font-bold mb-6">
              Performance <span className="text-g2c-blue">Specifications</span>
            </h2>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 gap-8">
            {specifications.map((spec, index) => (
              <Card key={index} className="text-center bg-card border-primary/20">
                <CardContent className="p-6">
                  <div className="text-2xl font-bold text-primary mb-2">{spec.value}</div>
                  <div className="text-sm text-muted-foreground">{spec.label}</div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Ideal Use Cases */}
      <section className="py-20 lg:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-5xl font-display font-bold mb-6">
              Ideal <span className="text-g2c-green">Use Cases</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {useCases.map((useCase, index) => (
              <Card key={index} className="bg-gradient-card border-primary/20">
                <CardHeader>
                  <CardTitle>{useCase.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">{useCase.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-hero">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl lg:text-5xl font-display font-bold mb-6">
            Ready to Power Your <span className="text-g2c-blue">Infrastructure?</span>
          </h2>
          <p className="text-xl text-muted-foreground mb-8 max-w-3xl mx-auto">
            Build the foundation for your artificial intelligence strategy with a data center engineered for the future of computing.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button variant="hero" size="lg" asChild>
              <Link to="/contact">
                Design Your AI Infrastructure
                <ArrowRight className="ml-2 h-5 w-5" />
              </Link>
            </Button>
            <Button variant="glass" size="lg" asChild>
              <Link to="/demo">Consult Our Experts</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AIReadyDataCenter;